# Generated by Django 4.1.3 on 2022-12-29 09:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usercnum', models.CharField(max_length=15, null=True)),
                ('useradd', models.CharField(max_length=200, null=True)),
                ('userplace', models.CharField(max_length=100, null=True)),
                ('userst', models.CharField(max_length=100, null=True)),
                ('userregd', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cconnectionid', models.CharField(max_length=10, null=True)),
                ('cconnectiontype', models.CharField(max_length=100, null=True)),
                ('cconnectionstartdate', models.DateField(null=True)),
                ('coccupation', models.CharField(max_length=100, null=True)),
                ('cconnectionload', models.CharField(max_length=100, null=True)),
                ('cplotno', models.CharField(max_length=50, null=True)),
                ('ccity', models.CharField(max_length=100, null=True)),
                ('cpincode', models.CharField(max_length=10, null=True)),
                ('caddress', models.CharField(max_length=200, null=True)),
                ('cstate', models.CharField(max_length=100, null=True)),
                ('cdescription', models.CharField(max_length=250, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billformonth', models.CharField(max_length=50, null=True)),
                ('crdayele', models.CharField(max_length=50, null=True)),
                ('prdayele', models.CharField(max_length=50, null=True)),
                ('dayelectu', models.CharField(max_length=100, null=True)),
                ('dayelechargeperunit', models.CharField(max_length=100, null=True)),
                ('crnightele', models.CharField(max_length=50, null=True)),
                ('prnightele', models.CharField(max_length=50, null=True)),
                ('nighteletu', models.CharField(max_length=100, null=True)),
                ('nightelechargeperunit', models.CharField(max_length=100, null=True)),
                ('crgas', models.CharField(max_length=50, null=True)),
                ('prgas', models.CharField(max_length=50, null=True)),
                ('gastotalunit', models.CharField(max_length=100, null=True)),
                ('gaschargeperunit', models.CharField(max_length=100, null=True)),
                ('standingcharge', models.CharField(max_length=50, null=True)),
                ('finalamount', models.CharField(max_length=100, null=True)),
                ('duedate', models.DateField(null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.connection')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.customer')),
            ],
        ),
    ]
