# Generated by Django 4.1.3 on 2022-12-29 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='customer',
        ),
        migrations.AlterField(
            model_name='bill',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.customer'),
        ),
    ]
