# Generated by Django 4.1.3 on 2022-12-29 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_remove_bill_customer_alter_bill_connection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connection',
        ),
    ]
